### ISSUE TITLE
Rompiendo el mundo binario con Vue.js

### ISSUE THREAD

**Issue by ianaya89** [meetupjs-ar/charlas#11]
### Título

Rompiendo el mundo binario con [Vue.js](http://vuejs.org/)
### Descripción

Con el release de su version 2, [Vue.js](http://vuejs.org/) quedo mas consolidado que nunca. Es sin duda una revelación el mundo MV\* client side y se posiciona como una de las alternativas mas prometedoras, peleando con gigantes de la industria como React y Angular 2. Voy a mostrarte la simpleza y el poder de este framework para que puedas considerarlo en tu proximo proyecto. 
### Sobre el orador

Full stack software engineer, mentor and field hockey player.

**Twitter:** [ianaya89](https://twitter.com/)
**Sitio:** [StackOverflow](http://stackoverflow.com/users/4195328/ianaya89)
### Recursos

**Slides de la presentación:** [LINK](https://ianaya89.github.io/breaking-the-binary-world/) 

**Repositorio de la charla:** [LINK](https://github.com/ianaya89/breaking-the-binary-world)
### Extra

Tenes la charla preparada?
No

En qué mes la podrías dar?
Febrero

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
NO

**Comment by nisnardi** [comment]
Confirmada esta charla para Febrero

**Comment by durancristhian** [comment]
Vamos @ianaya89! :D

**Comment by ianaya89** [comment]
👍🏻🎉😀

**Comment by keyserfaty** [comment]
@nisnardi este también

**Comment by nisnardi** [comment]
Gracias Nacho por esta charla!!

**Comment by p4bloch** [comment]
Comparto el link del video. Gracias @ianaya89!!
https://www.youtube.com/watch?v=ysx2Dpaju4w
