### ISSUE TITLE
La esencia de React

### ISSUE THREAD

**Issue by gabmontes** [meetupjs-ar/charlas#12]
### Título
La esencia de React

### Descripción
En esta charla les voy a contar un experimento que hice para entender la esencia de React, reimplementando sus partes más básicas, que definen su filosofía y simpleza. Si quieren un spoiler, lean [mi post en Medium](https://medium.com/@gab_montes/react-in-200-bytes-28156e714165) donde hice un primer intento. En esta charla podemos ir incluso un poco más allá.

### Sobre el orador
**Twitter:** @gab_montes

### Recursos
**Slides de la presentación:** TBD

**Repositorio de la charla:** (SPOILER) https://github.com/gabmontes/exploring-not-react

### Extra
Tenes la charla preparada?
Si.

En qué mes la podrías dar?
En cualquier momento.

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
Nada, gracias.

**Comment by leoasis** [comment]
Hola! 👋 Antes que nada te queremos decir gracias 🙏 por proponer una charla! Ya pasó bastante tiempo desde que la propusiste… y sabemos que en JS esto es una eternidad! 😂 

Es justamente por eso que te queremos preguntar si todavía estás con ganas de proponer una charla, si es esta misma, si es una actualización de la misma, o si es otra totalmente distinta. Necesitamos contar con información actualizada para poder elegir las charlas para las próximas meetups, y por eso es que te pedimos que nos ayudes.

Necesitaríamos que actualices la propuesta (o crees una nueva, como prefieras) con los campos de la charla actualizados a lo que tenés ganas de presentar hoy en día. Principalmente la descripción y la fecha en que podrías darla.

Muchas gracias y cualquier cosa podes contactarnos a cualquiera de la organización, o incluso aca seguir comentando en el issue.

**Comment by gabmontes** [comment]
@durancristhian actualicé el título y un toque la descripción. Ahora esperando luz verde de su lado!

**Comment by durancristhian** [comment]
💚 

👆 la luz verde jaja
mañana publicamos el evento con esta charla confirmada
