### ISSUE TITLE
Hice mi primer slackbot y te lo muestro

### ISSUE THREAD

**Issue by gabmontes** [meetupjs-ar/charlas#13]
### Título
Hice mi primer slackbot y te lo muestro

### Descripción
En esta charla les voy a mostrar lo fácil que es hacer un bot de Slack como para que cualquiera que tenga ganas pueda empezar a desarrollar uno y divertirse (o generar ingresos)! Vamos a usar el módulo [slackbots](https://www.npmjs.com/package/slackbots) y hacer una integración sencilla con una API externa.

### Sobre el orador
**Twitter:** gab_montes

### Recursos
**Slides de la presentación:** TBU

**Repositorio de la charla:** TBU

### Extra
Tenes la charla preparada?
No todavía.

En qué mes la podrías dar?
En cualquier momento.

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
Comida?

**Comment by leoasis** [comment]
Hola! 👋 Antes que nada te queremos decir gracias 🙏 por proponer una charla! Ya pasó bastante tiempo desde que la propusiste… y sabemos que en JS esto es una eternidad! 😂 

Es justamente por eso que te queremos preguntar si todavía estás con ganas de proponer una charla, si es esta misma, si es una actualización de la misma, o si es otra totalmente distinta. Necesitamos contar con información actualizada para poder elegir las charlas para las próximas meetups, y por eso es que te pedimos que nos ayudes.

Necesitaríamos que actualices la propuesta (o crees una nueva, como prefieras) con los campos de la charla actualizados a lo que tenés ganas de presentar hoy en día. Principalmente la descripción y la fecha en que podrías darla.

Muchas gracias y cualquier cosa podes contactarnos a cualquiera de la organización, o incluso aca seguir comentando en el issue.
