### ISSUE TITLE
Cross platform desktop apps con Electron

### ISSUE THREAD

**Issue by baromigue** [meetupjs-ar/charlas#14]
### Título
Cross-platform Desktop Apps con Electron

### Descripción
Desktop apps: NOT DEAD. Un vistazo general sobre Electron: la tecnología que nos permite desarrollar aplicaciones desktop coss-platform utilizando JavaScript, HTML y CSS! 
¿Qué es? ¿qué tecnología hay de fondo? ¿qué posibilidades ofrece? Además: comparación con otras tecnologías similares. Pros y Cons. Ejemplos de posibles aplicaciones y una breve introducción con los pasos para crear una app desde cero con esta tecnología.

### Sobre el orador
Soy desarrollador web desde hace 10 años. Actualmente soy full stack dev en SCVSoft.

**Twitter:** @baromigue

### Recursos
**Slides de la presentación:** TBD
**Repositorio de la charla:** TBD

### Extra
Tenes la charla preparada?
Casi. Me faltan algunos detalles.

En qué mes la podrías dar?
En cualquier momento

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

Conexión a internet y un proyector. 
Aclaro por las dudas que tengo un adaptador que es Thunderbolt a DVI. Si el proyector requiere otro tipo de conexión, voy a necesitar que me presten un adaptador adecuado.

**Comment by durancristhian** [comment]
Linda charla. 
Gracias

**Comment by morhook** [comment]
uhh..me la re perdí. Hay videos?
