### ISSUE TITLE
Lo que viene en fútbol de primera - Next.js 2.0

### ISSUE THREAD

**Issue by impronunciable** [meetupjs-ar/charlas#15]
### Título
Lo que viene en fútbol de primera - Next.js 2.0

### Descripción
[Next.js](https://github.com/zeit/next.js) ofrece una nueva forma de encarar aplicaciones web universales. Desde el lanzamiento del framework en Octubre aprendimos mucho acerca del uso que le da la comunidad al proyecto y se vienen grandes cambios para la segunda versión. Vamos a repasar la filosofía detrás de `next.js` para quien no lo conoce e introducir las nuevas features.

### Sobre el orador
**Twitter:** @impronunciable

**Sitio:** https://zajdband.com

### Recursos
**Slides de la presentación:** Coming soon

**Repositorio de la charla:** Coming soon

### Extra
Tenes la charla preparada? %25

En qué mes la podrías dar? Febrero

**Comment by nisnardi** [comment]
Confirmada esta charla para Febrero!

**Comment by keyserfaty** [comment]
@nisnardi podríamos cerrar este issue, no nico?

**Comment by nisnardi** [comment]
Gracias Dan por esta charla!!

**Comment by impronunciable** [comment]
Gracias a ustedes!

**Comment by p4bloch** [comment]
Agrego link con la charla en video. Gracias @impronunciable :)
https://www.youtube.com/watch?v=QxRaTHuRLGg
