### ISSUE TITLE
Entendiendo nuestras aplicaciones con Application Insights

### ISSUE THREAD

**Issue by GermanKuber** [meetupjs-ar/charlas#16]
### Título
Entendiendo nuestras aplicaciones con Application Insights

### Descripción
Liberar nuestra app a producción es solo el comienzo.
Conoce como se comporta tu aplicación en producción, entendé como los usuarios usan tu aplicación. 
Prevé errores, prevé fallos.

### Sobre el orador
**Twitter:** https://twitter.com/germankuber

**Sitio:** http://germankuber.com.ar/

### Recursos
**Slides de la presentación:** url de los slides de la presentación (si tenés)

**Repositorio de la charla:** url del repositorio con el código de la charla (si tenés)

### Extra
Tenes la charla preparada?
No
En qué mes la podrías dar?
Febrero/Marzo

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by leoasis** [comment]
Hola! 👋 Antes que nada te queremos decir gracias 🙏 por proponer una charla! Ya pasó bastante tiempo desde que la propusiste… y sabemos que en JS esto es una eternidad! 😂 

Es justamente por eso que te queremos preguntar si todavía estás con ganas de proponer una charla, si es esta misma, si es una actualización de la misma, o si es otra totalmente distinta. Necesitamos contar con información actualizada para poder elegir las charlas para las próximas meetups, y por eso es que te pedimos que nos ayudes.

Necesitaríamos que actualices la propuesta (o crees una nueva, como prefieras) con los campos de la charla actualizados a lo que tenés ganas de presentar hoy en día. Principalmente la descripción y la fecha en que podrías darla.

Muchas gracias y cualquier cosa podes contactarnos a cualquiera de la organización, o incluso aca seguir comentando en el issue.
