### ISSUE TITLE
Elm for World Peace

### ISSUE THREAD

**Issue by ajchambeaud** [meetupjs-ar/charlas#17]
### Título

Elm for World Peace

### Descripción

Una breve introducción a Elm contada por un programador frontend del clan react/redux. Si bien la charla no es sobre JS, esta dedicada a programadores JS y preparada por un programador JS. La idea es discutir algunas de las problemáticas que enfrenta la programación frontend moderna y como el paradigma funcional y el lenguaje elm en particular se proponen resolverlos. Siguiendo el espíritu de elm, vamos a hablar de los aspectos prácticos de la programación funcional, dejando de lado su aspecto mas académico (no hablaremos sobre category theory, monads, functors, etc).

Principales temas a tratar:

- Primeras impresiones sobre el lenguaje
- Programación funcional blanca y pura
- Programando sin nulls ni undefined
- Type safety
- Side effects
- Elm Architecture

Duración: 45min / 1hr

### Sobre el orador

**Twitter:** @ajchambeaud

**Sitio:** http://ajchambeaud.github.io/

### Recursos

**Slides de la presentación:** Prometo tenerlos listos un par de horas antes de la charla.

**Repositorio de la charla:** Todo el material de la charla estará disponible en Github como corresponde.

### Extra

Tenes la charla preparada?

Esta todo aquí [dedo indice apuntando a la cabeza]
(Es decir, no, no la tengo preparada :P) 

En qué mes la podrías dar?

Marzo estaría bien. A partir de entonces quedo a vuestra disposición.

**Comment by keyserfaty** [comment]
Confirmada esta chala para la Meetup de Marzo! :1st_place_medal:  :grin:
