### ISSUE TITLE
Programando aplicaciones en Bitcoin

### ISSUE THREAD

**Issue by yemel** [meetupjs-ar/charlas#18]
### Título
Programando aplicaciones en Bitcoin

### Descripción
Breve intro a Bitcoin. Ejemplos prácticos para crear, firmar y recibir transacciones en bitcoin.
Presentación de [Streamium.io](https://streamium.io), una app de micropagos en tiempo real.

### Sobre el orador
**Twitter:** yemeljardi

### Extra
Tenes la charla preparada? Soy profesor en el ITBA para la materia de grado de Bitcoin. Tengo gran parte del material listo, me falta ponerlo en una charla de 30 min.

Podría dar la charla en Mayo/Junio/Julio. 

Solo necesito conexión a internet y un proyector/monitor.

**Comment by leoasis** [comment]
Hola! 👋 Antes que nada te queremos decir gracias 🙏 por proponer una charla! Ya pasó bastante tiempo desde que la propusiste… y sabemos que en JS esto es una eternidad! 😂 

Es justamente por eso que te queremos preguntar si todavía estás con ganas de proponer una charla, si es esta misma, si es una actualización de la misma, o si es otra totalmente distinta. Necesitamos contar con información actualizada para poder elegir las charlas para las próximas meetups, y por eso es que te pedimos que nos ayudes.

Necesitaríamos que actualices la propuesta (o crees una nueva, como prefieras) con los campos de la charla actualizados a lo que tenés ganas de presentar hoy en día. Principalmente la descripción y la fecha en que podrías darla.

Muchas gracias y cualquier cosa podes contactarnos a cualquiera de la organización, o incluso aca seguir comentando en el issue.
