### ISSUE TITLE
Flow(type) for the Brave & True

### ISSUE THREAD

**Issue by mcortesi** [meetupjs-ar/charlas#19]
### Título
Flow(type) for the Brave & True

### Descripción
La idea es contar sobre [flowtype.org](flowtype.org) y nuestra experiencia en agregarlo a nuestro codebase en [Flowics](flowics.com).

No tengo pensada la charla, pero si tengo algunas ideas sobre que contar y que no:

  * Porque flow y no typescript. Cual fue nuestro analisis y conclusion
  * Muy breve intro a flow (no me gustaria detenerme mucho aca, porque creo que es algo que cualquiera aprende mirando la guia de flow)
  * Real world problems: How to solve X? (pasar por los diferentes problemas que te vas  a encontrar cuando realmente lo quieras usar, y nuestra experiencia en nuestra app. Es decir, node + react + redux + immutable.js + etc)  

### Sobre el orador
**Twitter:** @mcortesi5 

### Recursos
**Slides de la presentación:** todavía no

**Repositorio de la charla:** todavía no

### Extra
Tenes la charla preparada? No todavia, ideas en la cabeza. Pero hace un tiempo hablamos con leo y me tiro la idea de dar la charla.

En qué mes la podrías dar?

Necesito unas semanas de anticipacion para armar la charla, una vez que este cofirmada la misma. Podría llegar a marzo, o abril. Mayo yJunio depende la fecha porque me voy de viaje. Y sino cuando quieran

**Comment by durancristhian** [comment]
+1! Me gusta lo de "Porque flow y no typescript"

**Comment by durancristhian** [comment]
Gracias por esta charla :)
