### ISSUE TITLE
Progressive Web Apps con Ember

### ISSUE THREAD

**Issue by sdebarros** [meetupjs-ar/charlas#20]
### Título
Progressive Web Apps con Ember

### Descripción

Veremos qué es una PWA y cómo podemos desarrollar una aplicación web para móviles que aproveche las nuevas características de los navegadores más populares. Qué cosas nos ofrecen los mismos hoy para poder ofrecer una experiencia de usuario de primer nivel sin necesidad de instalar una app. Y cómo podemos, con Ember, desarrollar una aplicación web de estas características.

### Sobre el orador

Desarrolladora de software desde hace varios años, actualmente trabajo con tecnologías web, desarrollando principalmente en Ruby y Javascript (Ember).

**Github:** (@sdebarros)[https://github.com/sdebarros]

### Recursos
**Slides de la presentación:** -

**Repositorio de la charla:** -
### Extra
Tenes la charla preparada?
No, estoy en proceso de armado :)

En qué mes la podrías dar?
A partir de marzo.

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
👍

**Comment by keyserfaty** [comment]
Confirmada esta charla para la Meetup de Marzo! :1st_place_medal:  :grin:
