### ISSUE TITLE
RxJS

### ISSUE THREAD

**Issue by LuxDie** [meetupjs-ar/charlas#22]
### Título
Introducción a RxJS

### Descripción
Un vistazo a ReactiveX para JS, cómo difiere de observables, su relación con generadores y el paradigma que propone.

### Sobre el orador
Soy desarrollador web hace 10 años, trabajo principalmente en Frontend y soy Freelancer hace 1 año.

**Twitter:** https://twitter.com/SteelBlade

### Recursos
Nada aún.

### Extra
Tenes la charla preparada?
Esto es recién una idea, si a alguien le interesa colaborar sería genial.

En qué mes la podrías dar?
Junio quizás.

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by leoasis** [comment]
Hola! 👋 Antes que nada te queremos decir gracias 🙏 por proponer una charla! Ya pasó bastante tiempo desde que la propusiste… y sabemos que en JS esto es una eternidad! 😂 

Es justamente por eso que te queremos preguntar si todavía estás con ganas de proponer una charla, si es esta misma, si es una actualización de la misma, o si es otra totalmente distinta. Necesitamos contar con información actualizada para poder elegir las charlas para las próximas meetups, y por eso es que te pedimos que nos ayudes.

Necesitaríamos que actualices la propuesta (o crees una nueva, como prefieras) con los campos de la charla actualizados a lo que tenés ganas de presentar hoy en día. Principalmente la descripción y la fecha en que podrías darla.

Muchas gracias y cualquier cosa podes contactarnos a cualquiera de la organización, o incluso aca seguir comentando en el issue.

**Comment by LuxDie** [comment]
Dale, dejame que me organize y actualizo.

**Comment by LuxDie** [comment]
Cierro por falta de tiempo amigos.
