### ISSUE TITLE
Arquitecturas Empresariales Front-end, React, Redux, VanillaJS

### ISSUE THREAD

**Issue by andresmijares** [meetupjs-ar/charlas#23]
### Título
Agile Front End Enterprise Architectures with React, Redux and Vanilla JS.

### Descripción
Una propuesta genérica basada de arquitecturas front-end a nivel empresarial. Caso estudio Shiftgig.

### Sobre el orador
**Twitter:** [@andresmijares25](http://twitter.com/andresmijares25)

**Sitio:** [Medium Blog](https://medium.com/@andresmijares25)

### Recursos
**Slides de la presentación:** url de los slides de la presentación (si tenés)
TBD
**Repositorio de la charla:** url del repositorio con el código de la charla (si tenés)
TBD
### Extra
Tenes la charla preparada?
60%
En qué mes la podrías dar?
Mayo - Junio ++

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by gianu** [comment]
Hola @andresmijares!

Elegimos tu charla para le meetup de Junio (que va a ser el 21 de Junio). Queríamos saber si vas a poder darla, en cuyo caso decinos cual es tu username en el Slack de meetupJS para que podamos organizar por ese medio.

Sino tenes usuario todavía en meetupJS te invitamos a que te sumes en http://slack.meetupjs.com.ar/

**Comment by andresmijares** [comment]
@gianu genial! mi usuario es **andy** 

Saludos!

**Comment by leoasis** [comment]
Gracias Andres por tu charla! Estuvo muy buena!
