### ISSUE TITLE
PWA Garbarino - Una experiencia real

### ISSUE THREAD

**Issue by Villanuevand** [meetupjs-ar/charlas#25]
### Título
PWA Garbarino - Una experiencia real

### Descripción
Progressive web app es un término que está muy de moda. Mucho se habla sobre ellas pero poco se entiende realmente. En esta charla vamos a compartir la experiencia que vivimos construyendo la PWA de Garbarino de punta a punta, enfocándonos en los problemas y los aprendizajes más valiosos.

Un largo camino que involucró:
- Definición de Negocio
- Diseño
- Setup del proyecto
- Stack ... overflow.
- Desarrollo. (Service workers, funcionamiento Offline, APIs modernosas, Webpack).
- AB testing.
- Métricas y todas esas cosas que le gusta ver a los jefes.
- Y mucho más por venir...

### Sobre el orador
**Slack**: @leopittelli
**Twitter:** @leopittelli

### Recursos
**Slides de la presentación:** url de los slides de la presentación (si tenés)

**Repositorio de la charla:** url del repositorio con el código de la charla (si tenés)

### Extra
Tenes la charla preparada?
WIP.
En qué mes la podrías dar?
Agosto.

**Comment by durancristhian** [comment]
Gracias 👍
