### ISSUE TITLE
Destimificando Angular 2-4-10

### ISSUE THREAD

**Issue by jorgeucano** [meetupjs-ar/charlas#26]
### Título
Desmitificando Angular 2-4-10

### Descripción
Hay muchas opiniones encontradas en base a todos los frameworks y librerias que existen para FrontEnd hoy en día y una de las mas golpeadas en Angular (tal vez por su demora en salir a producción) pero Angular ofrece muchisimas mejoras y funcionalidades que no se conocen.. en esta charla veremos todas las funcionalidades que tiene angular en base a un ejemplo muy chico... Pasaremos por el CLI, RxJS, NGRx, Router entre otras cosas

### Sobre el orador
@jorgeucano
Después de más de 9 años desarrollando, Jorge es un full stack developer avocado a las tecnologías en javascript. Hoy en dia Jorge es un Full Stack Developer en ByteDefault utilizando Angular / RxJS / NodeJS / Firebase y otras tecnologías de punta… Profesor de varios cursos relacionados a javascript, Google Developer Expert en tecnologías web , Angular Developer Expert y Nativescript Developer Expert, speaker internacional, y escritor de artículos técnicos y un libro sobre Angular.

medium.com/@jorgeucano

### Recursos
Slide / Demo => github

### Extra
Tenes la charla preparada?
En un 50%

En qué mes la podrías dar?
Cuando sea posible

**Comment by leoasis** [comment]
Hola! 👋 Antes que nada te queremos decir gracias 🙏 por proponer una charla! Ya pasó bastante tiempo desde que la propusiste… y sabemos que en JS esto es una eternidad! 😂 

Es justamente por eso que te queremos preguntar si todavía estás con ganas de proponer una charla, si es esta misma, si es una actualización de la misma, o si es otra totalmente distinta. Necesitamos contar con información actualizada para poder elegir las charlas para las próximas meetups, y por eso es que te pedimos que nos ayudes.

Necesitaríamos que actualices la propuesta (o crees una nueva, como prefieras) con los campos de la charla actualizados a lo que tenés ganas de presentar hoy en día. Principalmente la descripción y la fecha en que podrías darla.

Muchas gracias y cualquier cosa podes contactarnos a cualquiera de la organización, o incluso aca seguir comentando en el issue.

**Comment by durancristhian** [comment]
Hola Jorge! Sigue en pie esta propuesta? Ayer vi que salió Angular 6 y creo que *Julio* puede ser un lindo momento dar esta charla. ¿Cómo lo ves? :)

**Comment by jorgeucano** [comment]
Hey @durancristhian seria genial ! hablemos de fechas para concordar que no pise nada y lo hacemos :D

**Comment by durancristhian** [comment]
Fecha no tenemos todavía, host tampoco (estamos laburando en planificar eso con tiempo). Calculo que será "como siempre", segunda o tercera semana del mes. Si te va, te confirmo, con tiempo vemos la fecha, pero te confirmo

**Comment by jorgeucano** [comment]
claro que si! firme como rulo de estatua (?)

**Comment by durancristhian** [comment]
La charla estuvo genial Jorge, muchas gracias :) en unos días la estaremos subiendo a youtube y te avisamos así la difundimos!
