### ISSUE TITLE
NativeScript: Javascript Nativo en tu celular

### ISSUE THREAD

**Issue by jorgeucano** [meetupjs-ar/charlas#27]
### Título
NativeScript: Javascript Nativo en tu celular

### Descripción
Nativescript es una plataforma que a travez de Angular te genera una app nativa para iOS y Android... a travez de esta charla veremos las ventajas que tiene este framework para poder crear apps con nuestros conocimientos

### Sobre el orador
@jorgeucano
Después de más de 9 años desarrollando, Jorge es un full stack developer avocado a las tecnologías en javascript. Hoy en dia Jorge es un Full Stack Developer en ByteDefault utilizando Angular / RxJS / NodeJS / Firebase y otras tecnologías de punta… Profesor de varios cursos relacionados a javascript, Google Developer Expert en tecnologías web , Angular Developer Expert y Nativescript Developer Expert, speaker internacional, y escritor de artículos técnicos y un libro sobre Angular.

medium.com/@jorgeucano

### Recursos

Slide / Demo => github

### Tenes la charla preparada?
En un 50%

### En qué mes la podrías dar?
Cuando sea posible

**Comment by leoasis** [comment]
Hola! 👋 Antes que nada te queremos decir gracias 🙏 por proponer una charla! Ya pasó bastante tiempo desde que la propusiste… y sabemos que en JS esto es una eternidad! 😂 

Es justamente por eso que te queremos preguntar si todavía estás con ganas de proponer una charla, si es esta misma, si es una actualización de la misma, o si es otra totalmente distinta. Necesitamos contar con información actualizada para poder elegir las charlas para las próximas meetups, y por eso es que te pedimos que nos ayudes.

Necesitaríamos que actualices la propuesta (o crees una nueva, como prefieras) con los campos de la charla actualizados a lo que tenés ganas de presentar hoy en día. Principalmente la descripción y la fecha en que podrías darla.

Muchas gracias y cualquier cosa podes contactarnos a cualquiera de la organización, o incluso aca seguir comentando en el issue.
