### ISSUE TITLE
StandupJS

### ISSUE THREAD

**Issue by jorgeucano** [meetupjs-ar/charlas#29]
### Título
StandUpJS

### Descripción
Standup sobre un programador javascript

### Sobre el orador
@jorgeucano

**Sitio:** medium.com/@jorgeucano

### Recursos
**Slides de la presentación:** nop

**Repositorio de la charla:** nop

### Extra
Tenes la charla preparada?
SI
En qué mes la podrías dar?
cuando quieran

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by Villanuevand** [comment]
¡Uhhh! terreno peligroso... @jorgeucano
