### ISSUE TITLE
npm como un campeón!

### ISSUE THREAD

**Issue by gabmontes** [meetupjs-ar/charlas#3]
### Título

npm como un campeón!
### Descripción

Vamos a charlar sobre comandos y trucos de `npm`, scripts, propiedades del `package.json`, etc. como para aprovechar esta herramienta más allá del típico `npm install`. 
### Sobre el orador

**Twitter:** @gab_montes
### Extra

Tenes la charla preparada?
No.

En qué mes la podrías dar?
Junio/julio

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
Gran picada con cervezas y tarta de ricota y dulce de leche!!

**Comment by p4bloch** [comment]
Me parece que te primereó @durancristhian!

**Comment by gabmontes** [comment]
Si, creo que con la charla de @durancristhian y algunas cosas de mi última charla en BA Node.JS en Medallia, el objetivo está cumplido.
