### ISSUE TITLE
Navegacion en React Native

### ISSUE THREAD

**Issue by elstr** [meetupjs-ar/charlas#32]
### Título
Navegacion en React Native
Algunas opciones para no caer en la locura.

### Descripción
Habiendo muchas opciones, vamos a ver un poco React Native Router Flux y React Native Navigation (wix).

### Sobre el orador
**Twitter:** usuario de Twitter (si tenés)
lele_lester

**Sitio:** url del sitio personal (si tenés)

### Recursos
**Slides de la presentación:** url de los slides de la presentación (si tenés)

https://slides.com/elstr/deck/

**Repositorio de la charla:** url del repositorio con el código de la charla (si tenés)

### Extra
Tenes la charla preparada?

En qué mes la podrías dar?

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by durancristhian** [comment]
Gracias por la charla (:
