### ISSUE TITLE
Expresiones regulares

### ISSUE THREAD

**Issue by tehsis** [meetupjs-ar/charlas#33]
### Título

Regex para todos

### Descripción
Usar y entender expresiones regulares es algo que puede servirnos trabajando en prácticamente cualquier lenguaje y Javascript, en particular, posee soporte first class para las mismas.
Sin embargo, muchos nos vemos abrumados al momento de usarlas o de entender una cuando se nos presenta. En esta charla voy a dar una breve introducción a las expresiones regulares, como leerlas y como armarlas usando una simple pero efectiva técnica. Además, claro de como usarlas dentro de nuestras aplicaciones JS.

### Sobre el orador
**Twitter:** @tehsis

**Sitio:** https://blog.tehsis.me

### Recursos
**Slides de la presentación:** url de los slides de la presentación (si tenés)

**Repositorio de la charla:** url del repositorio con el código de la charla (si tenés)

### Extra
El contenido de la charla esta basado en este blog post que escribí hace tiempo http://fernetjs.com/2013/07/introduccion-a-expresiones-regulares/ actualizandolo y haciendolo más didactico.

Podria dar la charla a principios de Junio en adelante.

Solo necesitaria un proyector para los slides y ejemplos.

**Comment by leoasis** [comment]
Hola! 👋 Antes que nada te queremos decir gracias 🙏 por proponer una charla! Ya pasó bastante tiempo desde que la propusiste… y sabemos que en JS esto es una eternidad! 😂 

Es justamente por eso que te queremos preguntar si todavía estás con ganas de proponer una charla, si es esta misma, si es una actualización de la misma, o si es otra totalmente distinta. Necesitamos contar con información actualizada para poder elegir las charlas para las próximas meetups, y por eso es que te pedimos que nos ayudes.

Necesitaríamos que actualices la propuesta (o crees una nueva, como prefieras) con los campos de la charla actualizados a lo que tenés ganas de presentar hoy en día. Principalmente la descripción y la fecha en que podrías darla.

Muchas gracias y cualquier cosa podes contactarnos a cualquiera de la organización, o incluso aca seguir comentando en el issue.

**Comment by durancristhian** [comment]
Hola @tehsis!, sigue en pie esta propuesta?

**Comment by durancristhian** [comment]
Me encantó la charla Pablo!, (y mucho más por las geniales partidas de lobo que se dieron más tarde jajaj). Gracias por sumarte!

En unos días estamos subiendo las charlas a youtube y te avisamos así les damos difusión
