### ISSUE TITLE
Construyendo a BarBot

### ISSUE THREAD

**Issue by mcampo** [meetupjs-ar/charlas#34]
### Título
Construyendo a BarBot

### Descripción
Un paseo por el proceso de desarrollo de BarBot, un dispenser de tragos robótico (programado con JS por supuesto).
En esta charla cuento cómo fué la experiencia, desde la idea hasta la implementación, pasando por el diseño, la fabricación digital (3D printing) y la programación.

### Sobre el orador
**Twitter:** [@tobillocrocante](https://twitter.com/tobillocrocante)

**Sitio:** ¯\\\_(ツ)\_/¯

### Recursos
**Slides de la presentación:** Todavía no

**Repositorio de la charla:** Aún no es público

### Extra
Tenes la charla preparada? No

En qué mes la podrías dar? Noviembre en adelante

**Comment by leoasis** [comment]
Hola! 👋 Antes que nada te queremos decir gracias 🙏 por proponer una charla! Ya pasó bastante tiempo desde que la propusiste… y sabemos que en JS esto es una eternidad! 😂 

Es justamente por eso que te queremos preguntar si todavía estás con ganas de proponer una charla, si es esta misma, si es una actualización de la misma, o si es otra totalmente distinta. Necesitamos contar con información actualizada para poder elegir las charlas para las próximas meetups, y por eso es que te pedimos que nos ayudes.

Necesitaríamos que actualices la propuesta (o crees una nueva, como prefieras) con los campos de la charla actualizados a lo que tenés ganas de presentar hoy en día. Principalmente la descripción y la fecha en que podrías darla.

Muchas gracias y cualquier cosa podes contactarnos a cualquiera de la organización, o incluso aca seguir comentando en el issue.

**Comment by mcampo** [comment]
Buenas! la charla sigue siendo la misma, solamente acutalizé la fecha en la que la podría dar.
