### ISSUE TITLE
Payments Revolution

### ISSUE THREAD

**Issue by ianaya89** [meetupjs-ar/charlas#40]
### Título
Payments Revolution

### Descripción
Hoy en dia muchos de los sitios de e-commerce pierden conversiones porque los usuarios abandonan las compras en la mitad del proceso. Y como no podia ser de otra manera, esos abandonos (en general) estan ligados a formularios complejos e ineficientes y a malas experiencias para el usuario.
Payment Request API viene a presentar una solucion para estos problemas, delegando  la responsabilidad de los formularios de pago a los browsers.
En esta charla voy a mostrarte como funciona esta nueva API, que funcionalidades ofrece y como 
podemos mejorar la experiencia del usuario a la hora de pagar en internet.

### Sobre el orador
**Twitter:** [ianaya89](https://twitter.com/ianaya89)

**Sitio:** [GitHub](https://github.com/ianaya89)

### Recursos
**Slides de la presentación:** No, todavia

**Repositorio de la charla:** No, todavia

### Extra
Tenes la charla preparada?
No, todavia

En qué mes la podrías dar?
Noviembre

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
No

**Comment by durancristhian** [comment]
Interesante charla Nacho, gracias por proponerla!

**Comment by leoasis** [comment]
Hola! 👋 Antes que nada te queremos decir gracias 🙏 por proponer una charla! Ya pasó bastante tiempo desde que la propusiste… y sabemos que en JS esto es una eternidad! 😂 

Es justamente por eso que te queremos preguntar si todavía estás con ganas de proponer una charla, si es esta misma, si es una actualización de la misma, o si es otra totalmente distinta. Necesitamos contar con información actualizada para poder elegir las charlas para las próximas meetups, y por eso es que te pedimos que nos ayudes.

Necesitaríamos que actualices la propuesta (o crees una nueva, como prefieras) con los campos de la charla actualizados a lo que tenés ganas de presentar hoy en día. Principalmente la descripción y la fecha en que podrías darla.

Muchas gracias y cualquier cosa podes contactarnos a cualquiera de la organización, o incluso aca seguir comentando en el issue.

**Comment by ianaya89** [comment]
Hola, no hay ningun problema 😄 
Podria ser para noviembre o mas adelante.

**Comment by durancristhian** [comment]
Sigue en pie esta propuesta Nacho? El tema es muy interesante y me gustaría tener la primicia en meetup.js 😘. Tenemos lugar disponible para Julio en adelante. Confirmame algún mes que te quede cómodo, así ya podés preparar el tema tranqui y nosotros asegurarnos esa charla :)

**Comment by ianaya89** [comment]
@durancristhian Obvio que sigue en pie. Podria ser en Agosto si te parece. Abrazo!!!

**Comment by durancristhian** [comment]
Si septiembre te va, te confirmo 👍🏼

**Comment by ianaya89** [comment]
Septiembre entonces. Confirmado!

**Comment by durancristhian** [comment]
Listo! Gracias Nacho!
