### ISSUE TITLE
Experiencia: Desarrollando avantrip.com con next.js, styled-components, redux, apollo, storybook, plop y excel (?)

### ISSUE THREAD

**Issue by qzapaia** [meetupjs-ar/charlas#42]
### Título
Experiencia: Desarrollando avantrip.com con next - styled-components - redux - apollo - storybook - plop y excel (?)

###  descripcion 
La idea es  contar como fue el proceso de decisiones de arquitectura y de uso de las herramientas con el desafío extra de un equipo recién entrando en React y con un proyecto planteado en tres meses de duración. No sería tanto código sino como llegamos a usar todo esto de una forma "decente" y no morimos en el intento.

### Sobre el orador
**Slack**: qzapaia

**Twitter:** qzapaia

### Recursos
**Slides de la presentación:** (todavía no)

**Repositorio de la charla:** (todavía no)

### Extra
Tenes la charla preparada?
Todavía no

En qué mes la podrías dar?
Octubre/Noviembre

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
Nope

**Comment by durancristhian** [comment]
Que interesante que se ve esta charla! Gracias por proponerla!

**Comment by p4bloch** [comment]
👍 Super Interesante!
