### ISSUE TITLE
Experiencia: Lecciones aprendidas desarrollando la app de AeroMéxico con React Native

### ISSUE THREAD

**Issue by alandawi** [meetupjs-ar/charlas#43]
**Título**
Lecciones aprendidas desarrollando la app de AeroMéxico con React Native

**Descripción**
Compartiremos las experiencias que tuvimos como equipo al desarrollar la aplicación de una aerolínea utilizando React Native, con todos los retos que esto puede representar. Detallaremos cómo afrontamos los problemas más importantes, junto con una visión objetiva del aprendizaje colectivo.
 
**Puntos a destacar**

- ¿Por qué React Native?
- Equipo grande de trabajo
- Integración de código web en React Native
- Navegación en React Native: Web is not App!
- Problemas
- Conclusiones

**Sobre los oradores**
![17796594_1852043195058533_2744885516424547893_n](https://user-images.githubusercontent.com/1291730/31449946-95f27528-ae7e-11e7-8c23-29f92252a63b.jpg)
Ronald Mendez es Ingeniero en Computación y actualmente trabaja como frontend developer en @Mediamonks Buenos Aires, donde desarrolla proyectos para campañas y plataformas. Adicionalmente, forma parte del jurado internacional de FWA, donde evalúa diariamente a algunos de los proyectos digitales más innovadores de la industria.

![dawi](https://user-images.githubusercontent.com/1291730/31449952-985249ba-ae7e-11e7-9f71-1db3b235115e.jpg)
Alan Dawidowicz (a.k.a 'Dawi') es programador y Técnico Multimedial. Trabaja actualmente en @MediaMonks Buenos Aires como JavaScript Developer. Estudió Licenciatura en Multimedia en la Universidad Maimónides. Trabajó como desarrollador en INIMA, inTacto, Almundo.com, entre otras.

![fabri](https://user-images.githubusercontent.com/1291730/31449954-99d6a24a-ae7e-11e7-86a0-210c82580c91.jpg)
Fabricio Mouzo es desarrollador y trabaja actualmente como JavaScript Developer en @Mediamonks Buenos Aires.

**Recursos**
Slides de la presentación:
Todavía no

Repositorio de la charla:
Todavía no

**Extra**

Tenes la charla preparada?
En proceso

En qué mes la podrías dar?
Octubre

**Comment by fjbotto** [comment]
wow, que bueno seria que puedan dar esta charla, trabajo en el sector y me serviría mucho el ejemplo!

**Comment by taniaborrego** [comment]
¿La Charla sigue en pie? Estoy muy interesada!

**Comment by fjbotto** [comment]
El meetup fue el Miercoles 18.
