### ISSUE TITLE
Ceci n'est pas un bouton.

### ISSUE THREAD

**Issue by evaferreira** [meetupjs-ar/charlas#45]
### Título
Ceci n'est pas un bouton.

### Descripción
HTML es accesible por default, somos nosotros los que en el día a día lo rompemos para crear experiencias fabulosas en la web. En esta charla les voy a mostrar cómo podemos romper HTML, crear unicornios y aún así, mantener la accesibilidad.

### Sobre el orador
**Twitter:** https://twitter.com/evaferreira92

### Recursos
**Repositorio de la charla:** https://github.com/evaferreira/accesibilidad-meetupjs

### Extra
Tenes la charla preparada? 80%
En qué mes la podrías dar? Noviembre

**Comment by durancristhian** [comment]
Gracias Eva, la charla estuvo muy buena!
