### ISSUE TITLE
Explorando la Web Descentralizada

### ISSUE THREAD

**Issue by peregrinogris** [meetupjs-ar/charlas#46]
### Título
Explorando la Web Descentralizada

### Descripción
El modelo tradicional de cliente-servidor en la web estaría teniendo una hermanita menor: la web peer-to-peer. Un mundo en dónde no hay distinción entre cliente y servidor, dónde la web se hace entre todos! Agarrá tu mejor capa de viajes, y vamos a explorar los secretos de esta nueva web!

### Sobre el orador
**Slack**: peregrino

**Twitter:** @peregrinogris

**Sitio:** 
 * http://peregrinogris.com.ar
 * dat://71e2b4835b01b3dbc64043a83d7fdba6fb5b5167da80e6770d0019e29a6d9d5d/

### Recursos
**Slides de la presentación:** TBD

**Repositorio de la charla:** TBD

### Extra
Tenes la charla preparada?
No todavía, está en pleno proceso de creación

En qué mes la podrías dar?
Diciembre 2017 o posterior.

**Comment by durancristhian** [comment]
Muy buena charla!
Muchas gracias :)
