### ISSUE TITLE
Sobre como medir performance de una SPA.

### ISSUE THREAD

**Issue by guadix** [meetupjs-ar/charlas#47]
### Título
Sobre como medir performance de una SPA.

### Descripción
Los browsers modernos tienen muchas herramientas nativas para medir performance. Mi propuesta es hacer un paneo sobre estas herramientas, y luego ver como se puede adecuar a las necesidades de las SPAs.

### Sobre el orador
**Slack**: Guadalupe Reyes (Guada)

### Recursos
**Slides de la presentación:** No aun

**Repositorio de la charla:** No aun

### Extra
No

Diciembre o después

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by durancristhian** [comment]
Muy buena charla!
Muchas gracias :)
