### ISSUE TITLE
Apollo 2: apollo-link-state como alternativa de Redux

### ISSUE THREAD

**Issue by qzapaia** [meetupjs-ar/charlas#48]
### Título
apollo-link-state como alternativa de Redux

### Descripción
La idea es mostrar brevemente los cambios que trae Apollo 2 con respecto a la version 1 y entender la propuesta de link-state como alternativa al state manager que usemos (Redux).

### Sobre el orador
**Slack**:  qzapaia

**Twitter:** qzapaia

### Extra
Tenes la charla preparada?
Todavía no.

En qué mes la podrías dar?
Enero/Febrero ?

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
Nad

**Comment by durancristhian** [comment]
Hola Marce, gracias por la propuesta!

Generalmente no hacemos meeutps en enero y febrero, porque hay mucha gente de vacaciones y demás. Obvio que la vamos a tener en cuenta cuando estemos armando los eventos que siguen.

Gracias de nuevo!
