### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by julioolvr** [meetupjs-ar/charlas#49]
### Título
WebAssembly, o para qué programar en JavaScript cuando podemos escribir assembler

### Descripción
Contar un poco qué es WASM, para qué sirve y mostrar ejemplos de uso

### Sobre el orador
**Slack**: `@julito`

**Twitter:** [@julioolvr](https://twitter.com/julioolvr)

**Sitio:** [joliv.me](http://joliv.me/)

### Recursos
**Slides de la presentación:** https://slides.com/julioolvr/wasm

**Repositorio de la charla:** Un poco de [julioolvr/how-to-wasm](https://github.com/julioolvr/how-to-wasm/) y un poco de [julioolvr/rlox](https://github.com/julioolvr/rlox), pero ninguno es específico de la charla

### Extra
Tenes la charla preparada?
Un 80%, me falta el otro 80%

En qué mes la podrías dar?
Febrero en adelante

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
N/A

**Comment by julioolvr** [comment]
@durancristhian perfecto, me va 👍

**Comment by durancristhian** [comment]
Genial, gracias por la pronta respuesta.

**Comment by durancristhian** [comment]
Terrible charla! Gracias por sumarte. Dentro de poco subiremos los videos :)
