### ISSUE TITLE
Un tour por Team Fundation Service

### ISSUE THREAD

**Issue by GermanKuber** [meetupjs-ar/charlas#5]
### Título

Un tour por Team Fundation Service
### Descripción

No es un IDE, que es todo lo demás. Visual Studio Team Services proporciona un conjunto de herramientas de colaboración en la nube potencia que trabajan con su editor o IDE existente, por lo que su equipo puede trabajar eficazmente en proyectos de software de todas las formas y tamaños.
### Sobre el orador

**Twitter:** https://twitter.com/germankuber
### Recursos

**Repositorio de la charla:** https://github.com/GermanKuber/Presentaciones-Microsoft-Azure
### Extra

Si

Agosto

**Comment by nisnardi** [comment]
Hola Ger

Si te parece bien podemos meter esta charla para la meetup de Octubre. Seguimos la charla por slack para terminar de organizar.

**Comment by p4bloch** [comment]
Gracias Germán!
