### ISSUE TITLE
Redux²: using your state both in React and React Native apps

### ISSUE THREAD

**Issue by freynolds** [meetupjs-ar/charlas#51]
### Título
Redux²: using your state both in React and React Native apps

### Descripción
El buen uso de Redux ya nos soluciona tantos problemas que es casi imposible no agregarlo como un must en un proyecto mediano.
En esta charla pretendo mostrar distintas maneras de estructurar tu app en React y como hacer para duplicar tu codigo y reutilizar el state en web y native.

### Sobre el orador
**Slack**: freynolds

**Twitter:** francisreynolds

Soy Francisco Reynolds, frontend Dev en Toptal, entre muchas cosas hice el sitio messi.com, la app de mi telefe y la app del trece tv. Fui orador de la NSConfArg 2017 y futuro orador de la iOSDevUK 2018. Cuando no estoy trabajando me gusta salir a remar por el delta y viajar por el mundo

### Extra
Tenes la charla preparada?
No

En qué mes la podrías dar?
Marzo, Junio, …

**Comment by durancristhian** [comment]
Buenas! @freynolds Sigue en pie esta propuesta? Nos gustaría escuchar esta charla

**Comment by durancristhian** [comment]
Mañana publicamos el evento, esta charla está confirmada :)
