### ISSUE TITLE
De local a global con un comando

### ISSUE THREAD

**Issue by sergiodxa** [meetupjs-ar/charlas#52]
### Título
De local a global con un comando

### Descripción
En la charla veremos como usar Now para llevar una aplicación Node.js, un contenedor de Docker o un sitio estático de nuestra computadora a producción y escalarlo para que funcione de forma global.

Y vamos a aprovechar para repasar las ventajas de serverless.

### Sobre el orador
**Slack**: @sergiodxa

**Twitter:** [@sergiodxa](https://sdx.im/twitter)

**Sitio:** https://sergiodxa.com

### Recursos
**Slides de la presentación:** https://sergiodxa.com/slides/local-to-global

**Repositorio de la charla:** No hay

### Extra
Tenes la charla preparada?
Estoy en eso

En qué mes la podrías dar?
En Octubre/Noviembre voy a estar en CABA, Cualquier otro mes podría ser online.

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
Si es presencial un adaptador USB-C para conectar el proyector para Mac e internet.

**Comment by durancristhian** [comment]
Excelente propuesta! Gracias

**Comment by durancristhian** [comment]
Se que falta mucho, pero tenés fechas en las que vas a estar acá? el 18, 19 y 20 de octubre es la NodeConf así que el evento de octubre seguro lo haremos a principio a octubre y el de noviembre quizás a partir de la segunda semana. Sea como sea, quiero darle prioridad a esta charla y armar el evento en base a eso, espero que no te complique la vida esto.

**Comment by sergiodxa** [comment]
Todavía no tengo fechas definitivas (AKA no compré los pasajes), fecha tentativa es desde la última semana de octubre y hasta la última de noviembre.
