### ISSUE TITLE
¿Se puede hacer eso con JSX?

### ISSUE THREAD

**Issue by pomber** [meetupjs-ar/charlas#58]
### Título
¿Se puede hacer eso con JSX?

### Descripción
¡Esta charla **no** es sobre React! 
JSX permite describir árboles (la estructura de datos, no la planta) con algo parecido a XML dentro de código JavaScript. Si bien el mejor caso de uso para JSX es describir árboles de elementos de React, eso no quiere decir que no se pueda usar para otras cosas.

### Sobre el orador

[@pomber](https://twitter.com/pomber)

### Recursos

Basada en este [post](https://engineering.hexacta.com/jsx-can-do-that-1b2666c23a32).

### Extra

* **Tenes la charla preparada?**: Tengo el contenido, solo me falta formatearlo en forma de charla
* **A partir de que mes la podrías dar?:** Agosto

**Comment by durancristhian** [comment]
Confirmada para Agosto 💪
Más sobre la fecha hablamos!

**Comment by durancristhian** [comment]
Muy buena charla. Gracias por sumarte. Dentro de poco subiremos los videos :)
