### ISSUE TITLE
Cómo estamos migrando nuestra API REST a GraphQL en Restorando

### ISSUE THREAD

**Issue by jfresco** [meetupjs-ar/charlas#6]
### Título

Cómo estamos migrando nuestra API REST a GraphQL en Restorando
### Descripción

En Restorando decidimos probar GraphQL y nos fue tan bien que las apps mobile ya lo están usando en Producción.
Ahora queremos migrar nuestras web apps a React y como capa de conexión al backend empezamos usando Relay. Luego decidimos sacarlo y reemplazarlo por Redux.
Te voy a contar cómo nos fue, qué nos salió bien, en qué nos equivocamos y qué tenemos planeado para el futuro.
### Sobre el orador

**Twitter:** jfresco82

**Sitio:** http://github.com/jfresco
### Recursos

**Slides de la presentación:** --

**Repositorio de la charla:** --
### Extra

Tenes la charla preparada? No

En qué mes la podrías dar? Septiembre

**Comment by p4bloch** [comment]
José, oficialmente te confirmo la charla para principios de Octubre, así de paso le damos continuidad a la introducción que vimos hoy. Hablamos los detalles por Slack. Gracias!

**Comment by p4bloch** [comment]
Gracias José!
