### ISSUE TITLE
Sobre las cartas la mesa

### ISSUE THREAD

**Issue by impronunciable** [meetupjs-ar/charlas#60]
# ⚠️ IMPORTANTE

### Título
Sobre las cartas la mesa

### Descripción
Vamos a ver técnicas simples de reconocimiento de input en la web para que tus usuarios te amen sin privarte del sueño

### Sobre el orador

* **Bio**: Dan es un programador Argentino. Trabajó y formó parte en proyectos open source como el Coral Project, Next.js y algunos otros que seguramente usaron. Ahora está trabajando en un banco digital para Argentina que sale pronto.

* **Foto**: https://pbs.twimg.com/profile_images/861778972421611521/B02y_Rq9_400x400.jpg
* **Usuario de Twitter**: @impronunciable

### Recursos

* **Slides de la presentación**: La presentación sale de mi artículo https://source.opennews.org/articles/low-budget-natural-language-processing/

### Extra

* **Tenes la charla preparada?**: Casi
* **A partir de que mes la podrías dar?:** Septiembre

**Comment by durancristhian** [comment]
Confirmada para septiembre! 💪
Más sobre la fecha hablamos
