### ISSUE TITLE
Star Wars: React, Vue y el Futuro del Frontend.

### ISSUE THREAD

**Issue by ajchambeaud** [meetupjs-ar/charlas#62]
### Título
Star Wars: React, Vue y el Futuro del Frontend.

### Descripción
"Todos necesitamos un nemesis. Sherlock Holmes tenia al Dr. Moriarty, Superman tenia al pinguino, y hasta Maggie tiene un bebe que la ve feo" L.S.

Este año la comunidad de Vue celebro una victoria contra React (luego de una épica batalla) por ver quien juntaba mas estrellas en GitHub. La batalla pudo seguirse en vivo en este sitio: https://hasvuepassedreactyet.surge.sh/ y tras unas semana en la que ambas librerias sumaron mas de 20k estrellas cada una, se termino confirmando una tendencia favorable a Vue por unas 1000 estrellas al momento de escribir este texto. 

Este podrá parecer insignificante para muchos, pero es una señal de que hay un nuevo actor en escena, si bien la penetración en la industria es claramente menor a React (al menos a la fecha). 

Temas de la charla:

- Diferencias filosoficas y conceptuales entre Vue y React.
- Similitudes entre ambas librerias.
- Como programador React, usaria Vue para mi próximo proyecto?
- Como programador React, que cosas envidio de Vue?
- Algunos consejos para abordar la próxima guerra de frameworks con serenidad heideggeriana.

(Disclaimer: puede que la charla no sea del todo neutral :agite:)

### Sobre el orador

* **Bio**: 

Soy programador web hace 8 años y también me gusta dar clases cuando el tiempo me lo permite. Me dedico principalmente al desarrollo de interfaces y trabajo con React desde hace 3 años. Soy bastante fana de la programacion funcional y me gusta explorar lenguajes y tecnologias alternativas como Elm y Reason.

* **Foto**: 

https://pbs.twimg.com/profile_images/1019713218086883328/zPiNmtjc_400x400.jpg

* **Usuario de Slack**: 

@ajchambeaud 

* **Usuario de Twitter**: 

@ajchambeaud 

### Recursos

* **Slides de la presentación**:  TBD
* **Repositorio de la charla**:  TBD

### Extra

* **Tenes la charla preparada?**:  

No todavía

* **A partir de que mes la podrías dar?:** 

Cuando ustedes digan

> Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

Nope

**Comment by durancristhian** [comment]
que buena charla! gracias por proponerla.

**Comment by durancristhian** [comment]
@ajchambeaud _Superman tenia al pinguino_? Creo que viste otra película 🤔

**Comment by ajchambeaud** [comment]
https://www.youtube.com/watch?v=2uxKBNplCs8
