### ISSUE TITLE
From HTML + CSS to React + Styled Components

### ISSUE THREAD

**Issue by sergiofruto** [meetupjs-ar/charlas#65]
### Descripción
Cómo empezar a trabajar en React sin volverse loco (un poco si.) La idea es contar mi experiencia como maquetador empezando a trabajar con React y Styled Components on a daily basis. 
Pequeños tips, patrones, Dos and don'ts, cosas que te van a ayudar en el viaje y cosas que nos pasaron en un caso real migrando el sitio de Auth0. 

### Sobre el orador

* **Bio**:  Sergio. UI Developer @ Auth0
* **Foto**: https://pbs.twimg.com/profile_images/995719630302916610/N2KTF0DP_400x400.jpg
* **Usuario de Slack**:  @checho
* **Usuario de Twitter**: @sergiofruto

### Recursos

* **Slides de la presentación**:  
* **Repositorio de la charla**: 

* **Tenes la charla preparada?**: Necesito ayuda parar prepararla :)
* **A partir de que mes la podrías dar?:**  Noviembre

> Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by durancristhian** [comment]
Gracias checho! estuvo genial. Gracias por animarte
