### ISSUE TITLE
Whose error is it anyway

### ISSUE THREAD

**Issue by hrajchert** [meetupjs-ar/charlas#66]
### Título
Whose error is it anyway

### Descripción
Cuando progamamos, solemos concentrarnos en el camino feliz, resolviendo la tarea principal suponiendo que nada puede malir sal. Lamentablemente todo lo que puede pasar va a pasar, así que cuando queramos abrir nuestros archivos de configuraciones, los archivos no estaran o tendrán un formato inválido, cuando queramos guardar un usuario la base estará caida y cuando consultemos al backend el servidor dará timeout.

Cómo hacemos entonces para manejar nuestros errores? En esta charla veremos cómo podemos usar TypeScript para no volvernos locos y manejar correctamente lo que sale bien y lo que sale mal.

### Sobre el orador

* **Bio**: Soy Hernán pero me dicen Sherman, me gustan los lenguajes tipados y la programación funcional. 
* **Foto**: https://scontent-eze1-1.xx.fbcdn.net/v/t1.0-9/44897536_2122712247981095_8993300641786888192_o.jpg?_nc_cat=106&_nc_ht=scontent-eze1-1.xx&oh=e9e427e39e99d3efdb5b94e3f1276979&oe=5C3CC3FA
* **Usuario de Slack**: @sherman
* **Usuario de Twitter**: @sherman3ero

### Recursos

* **Slides de la presentación**: Todavía no.
* **Repositorio de la charla**: Todavía no

### Extra

* **Tenes la charla preparada?**: No
* **A partir de que mes la podrías dar?:** Enero 2019

**Comment by durancristhian** [comment]
Gracias colega! La rompiste!

**Comment by hrajchert** [comment]
:partyparrot:
