### ISSUE TITLE
Que ir al cine no sea un drama

### ISSUE THREAD

**Issue by lndgalante** [meetupjs-ar/charlas#67]
### Título
Que ir al cine no sea un drama [Lightning Talk]

### Descripción
Vamos a ver como podemos prototipar rápidamente una mejor experiencia para comprar una entrada de cine 🎦. Además como los side-projects nos ayudan a salir de nuestra área de comfort, aprender nuevas tecnologías, y entender que es lo que quieren los usuarios.

Thread: https://twitter.com/lndgalante/status/1057432179914010625

### Sobre el orador

* **Bio**: Leonardo Galante, desarrollador front-end, organizo freeCodeCampBA, me gusta aprender/enseñar y me gusto preferido de helado es el limón 🍋
* **Foto**: https://i.imgur.com/QQvyZpE.jpg
* **Usuario de Slack**: @leog
* **Usuario de Twitter**: @lndgalante

### Recursos

* **Slides de la presentación**: no todavía
* **Repositorio de la charla**: no todavía

### Extra

* **Tenes la charla preparada?**: No todavía
* **A partir de que mes la podrías dar?:** Diciembre 2018

**Comment by durancristhian** [comment]
Gracias capo!
