### ISSUE TITLE
Take on me, web browsers!

### ISSUE THREAD

**Issue by evaferreira** [meetupjs-ar/charlas#69]
### Título
Take on me, web browsers!

### Descripción
En 1985 el mundo bailó al ritmo de “Take on me”, de la banda noruega A-ha. Pero no solo fue la música lo que encantó, sino [el vídeo que lo acompañaba](https://www.youtube.com/watch?v=djV11Xbc914). Pasaron casi 35 años y aún podemos disfrutar nuevos vídeos con la misma técnica de animación con rotoscopia que se aplicó en ese entonces. Pero... ¿En la web? ¿Cómo logramos editar vídeo a esa altura? ¿Podríamos… Hacer Chroma Key con JavaScript?

### Sobre el orador

* **Bio**: Eva Ferreira disfruta de leer drafts de la W3C tanto como Harry Potter.
* **Foto**: https://drive.google.com/open?id=1cN0cREQD1-YnwDeeRaEIVah8bOCdyOCW 
* **Usuario de Twitter**: evaferreira92

### Recursos

* **Slides de la presentación**: Próximamente
* **Repositorio de la charla**: Próximamente

### Extra

* **Tenes la charla preparada?**: 40%-ish
* **A partir de que mes la podrías dar?:** Abril, solo puedo lunes, miércoles y viernes (perdón!)

**Comment by durancristhian** [comment]
Gracias por proponer la charla Eva!

**Comment by durancristhian** [comment]
Salió genial la charla Eva. Cierro el issue y esperamos en los próximos días tener las charlas listas para publicarlas. Te aviso antes de publicar todo.
