### ISSUE TITLE
Visual Diffing tools should be for everyone

### ISSUE THREAD

**Issue by lndgalante** [meetupjs-ar/charlas#71]
### Título
Visual Diffing tools should be for everyone

### Descripción
Muchas herramientas de visual diffing necesitan de cierto conocimiento y configuración, la idea que alguien de otra área como el área comercial o de diseño pueda comparar un frontend con un diseño estático de manera rápida y fácil y esto es lo que busca solucionar Diffy.

### Sobre el orador

* **Bio**: Leonardo Galante, desarrollador front-end, organizo freeCodeCampBA, me gusta aprender/enseñar y me gusto preferido de helado es el limón 🍋
* **Foto**: https://i.imgur.com/QQvyZpE.jpg
* **Usuario de Slack**: @leog
* **Usuario de Twitter**: @lndgalante

### Recursos

* **Slides de la presentación**: undefined
* **Repositorio de la charla**: undefined

### Extra

* **Tenes la charla preparada?**: undefined
* **A partir de que mes la podrías dar?:** Junio 2019

**Comment by leog** [comment]
Tengan cuidado de mencionar un usuario de GitHub con el nombre de un usuario de otra plataforma. Me llegó una notificación de este  ticket 😅
