### ISSUE TITLE
JavaScript: Entre Java y Haskell

### ISSUE THREAD

**Issue by ajchambeaud** [meetupjs-ar/charlas#72]
# ⚠️ IMPORTANTE

> Por favor, te pedimos que completes este issue lo más posible para evitar andar contactándote más veces para pedirte esta información.

### Título
JavaScript: Entre Java y Haskell

### Descripción
Gran parte de la comunidad de JavaScript espera que el lenguaje evolucione (como plataforma) evolucione, pero no todos están de acuerdo en cómo debería evolucionar. Con el pasar de los años creo haber identificado 2 tendencias: aquellos usuarios que quisieran que JS sea Java y aquellos que desearían que se convierta en Haskell. El propósito de esta charla es discutir informalmente sobre el futuro y pasado de JS haciendo énfasis en la filosofía del lenguaje y pasando por clickbait topics como OOP vs FP, Static vs Dynamic, ES6+, TS, Flow.

### Sobre el orador

* **Bio**: Me dedico profesionalmente al desarrollo de software hace unos 9 años, de los cuales los últimos 5 los invertí casi exclusivamente en JavaScript y los últimos 4 en React. Soy un entusiasta de la programación funcional y de los lenguajes de la familia ML (Que significa Meta Language y no Machine Learning). 

* **Foto**: https://pbs.twimg.com/profile_images/1128451468565131265/ISIzdwe8_400x400.jpg

* **Usuario de Slack**: ajchambeaud

* **Usuario de Twitter**: ajchambeaud

* **Otros usuarios**: 

### Recursos

* **Slides de la presentación**: TBD
* **Repositorio de la charla**: TBD

### Extra

* **Tenes la charla preparada?**: Casi.

* **A partir de que mes la podrías dar?:** A partir de este mes

> Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by durancristhian** [comment]
Excelente charla colega. Me gustó mucho y aprendí como con todas las que nos diste. Cierro el issue. Hablamos pronto y te aviso cuando estén las charlas listas para ser publicadas.
