### ISSUE TITLE
Mono-Repos & Bazel FTB-uild

### ISSUE THREAD

**Issue by jorgeucano** [meetupjs-ar/charlas#74]
# ⚠️ IMPORTANTE

> Por favor, te pedimos que completes este issue lo más posible para evitar andar contactándote más veces para pedirte esta información.

### Título
Mono-Repos & Bazel FTBuild

### Descripción
PayPal, Dropbox, Google, Huawei, Stripe, Pinterest, entre otros gigantes de la tecnología, tienen una cosa en común (además de millones de dólares), usan la misma arquitectura, la magia
de "Mono-Repos" a un solo repositorio para TODOS tus proyectos ...

What?????

Bazel is your friend my friend! 
en los 40 minutos vamos a ver como usar una arquitectura de mono-repo y bazel vamos a poder hacer builds increiblemente rapidos, con validaciones de librerias y distintos lenguajes de programacion (obvio que le vamos a meter un poquito de angular)
### Sobre el orador

* **Bio**: 
Después de más de 10 años desarrollando, Jorge es un full stack developer avocado a las tecnologías en javascript. Hoy en dia Jorge trabaja como “principal engineer” en HeroDevs utilizando Angular / RxJS / NodeJS / Firebase y otras tecnologías de punta… Profesor de varios cursos relacionados a javascript, Google Developer Expert en tecnologías web , Angular Developer Expert y Nativescript Developer Expert, speaker internacional, escritor de artículos técnicos y un libro sobre Angular.

* **Foto**: 
https://pbs.twimg.com/profile_images/1088779016675430401/xDyQaZ0w_400x400.jpg

* **Usuario de Slack**: @jorgeucano
* **Usuario de Twitter**: @jorgeucano

### Recursos

* **Slides de la presentación**: WIP
* **Repositorio de la charla**: WIP

### Extra

* **Tenes la charla preparada?**: SI
* **A partir de que mes la podrías dar?:** now

> Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
que sepan que los quiero <3

**Comment by mateosilguero** [comment]
Gracias Jorge !
