### ISSUE TITLE
About life, robots and cats!

### ISSUE THREAD

**Issue by ConstanzaYC** [meetupjs-ar/charlas#79]
# ⚠️ IMPORTANTE

> Por favor, te pedimos que completes este issue con toda la información requerida y lo más detallado posible para evitar pedirte datos faltantes, de esta forma hacemos más eficiente el proceso de selección de charlas.

### Título
About life, robots and cats!

### Descripción
Cuando era chiquita solía tener sueños recurrentes en los que inventaba robots que me ayudab an a hacer algunos quehaceres de la casa, como por ejemplo hacer la cama, lavar los platos, guardar mis juguetes, etc.
Eso fue solo un sueño hasta que crecí, me metí en el mundo de la programación y encontré algo llamado Home Automation. Puse manos a la obra y construí a Sasha, un alimentador de mascotas que me cambió la vida y también la de mis gatos.

Quiero compartir con ustedes el camino que hice para construir a Sasha usando JavaScript, cables y motorcitos.-

### Tus datos

* **Bio**: Constanza es programadora Front-End, es parte del equipo organizador de Chicas Programando y colabora en distintas comunidades de programación. Su interés es generar espacios inclusivos y diversos para todas las personas en el rubro tecnológico. Tiene dos gatos, Orson y Haku. #TeamBatata y del equipo de Palta Forever.

* **Foto**: https://drive.google.com/open?id=18fBA_j8TodZg4bA4IhnDjnLd_JdHVizG

* **Usuario de Slack**: ConstanzaYC
* **Usuario de Twitter**: @co_constanza
* **Otros usuarios**: Si no tenés Twitter dejanos acá otros links donde te gustaría que te mencionemos en los tweets y otras publicaciones.
* **Pronombre**: Ella

### Recursos

* **Slides de la presentación**: URL de la presentación (Si tenés).
* **Repositorio de la charla**: URL del repositorio con el código de la charla (Si tenés).

### Extra

* **¿Tenés la charla preparada?**: Sí.
* **¿A partir de qué mes la podrías dar?:** Fines de agosto, septiembre, noviembre.

> Avisanos si necesitás algo especial para poder dar la charla así lo podemos planificar con tiempo: una mesa para apoyar el alimentador

**Comment by mateosilguero** [comment]
Gracias Co !
