### ISSUE TITLE
Introduccion al desarrollo de VJ con PhaserJS

### ISSUE THREAD

**Issue by shadowofsoul** [meetupjs-ar/charlas#81]
# ⚠️ IMPORTANTE

> Por favor, te pedimos que completes este issue con toda la información requerida y lo más detallado posible para evitar pedirte datos faltantes, de esta forma hacemos más eficiente el proceso de selección de charlas.

### Título
Introduccion al desarrollo de VJ con PhaserJS

### Descripción
Hacer VJ es un mundo en si mismo. Es donde la complejidad tecnica se mezcla con la creatividad. Es donde el gamedev debe tener un delicado balance entre la creacion de una experiencia interactiva inmersiva para el usuario y los procesos tecnicos que requiere hacerla realidad. Pretendo explicar la estructura tecnica de un VJ, su estructura ludica, en como lo diferentes elementos interactuan entre si (gameplay, musica, sfx, AI), y cuales son las herramientas tecnicas (main loop, eventos, tempo en VJ) necesarias para llevar estos elementos a una pieza de software unica. Usando PhaserJS para los ejemplos practicos (y explicando su API basica). Finalizando con tecnicas de adaptacion de contenido multiplataforma, Como y donde publicar tu VJ y lo que considero, lo mas importante en el desarrollo de VJ: enfoque en la experiencia.

### Tus datos

* **Bio**: CEO de Ipsilon Developments. 10+ años programando en web, VJ y electronica. Si existe, en algun momento lo toque o lo rompi. Cuando estoy quemado, me pongo a cocinar postres (preferentemente sin azucar)

* **Foto**: 
![IMG_20190411_200140_468](https://user-images.githubusercontent.com/375696/63524744-eb37f500-c4d2-11e9-8a2c-d1d96a3f32ed.jpg)

* **Usuario de Slack**: shadowofsoul
* **Usuario de Twitter**:  shadow_of__soul
* **Pronombre**: Lord of the universe

### Recursos

* **Slides de la presentación**:  [https://docs.google.com/presentation/d/1IXTeAM5ijcKCJm41lkkrhkdFNbgntCXvA3POAvNQSzA/edit?usp=drivesdk](aqui estan)
* **Repositorio de la charla**: no es necesario

### Extra

* **¿Tenés la charla preparada?**: Si
* **¿A partir de qué mes la podrías dar?:** Cuando quieras, avisame 1 semana antes aunque sea por si tengo algun viaje

> Avisanos si necesitás algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by durancristhian** [comment]
QUE BIEEEEN ❤️

**Comment by mateosilguero** [comment]
Gracias David !
