### ISSUE TITLE
Testing en el mundo del Frontend

### ISSUE THREAD

**Issue by sergiodxa** [meetupjs-ar/charlas#84]
### Título
Testing en el mundo del Frontend

### Descripción
Repaso por las diferentes formas y técnicas para hacer testings y darnos seguridad de que nuestra aplicación Frontend va a funcionar, empezando por linters, pasando por tippado, unit tests, snapshots, test de integración y terminando con end-to-end. Todo viendo ejemplo con código.

### Tus datos

**Bio**: Sergio Xalambrí aprendió programación de forma autodidacta y trabaja como Tech Lead en Able. Lidera Tech Talks Perú. Es contribuidor de varias librerías de código abierto en JavaScript, incluyendo Next.js, micro, serve, Now CLI y más. Dictó cursos online y talleres presenciales de React, Redux y ZEIT Now en Colombia como parte del equipo de Platzi. Es también autor del libro "Desarrollo de Aplicaciones Web con React.js y Redux.js".
* **Foto**: https://avatars1.githubusercontent.com/u/1312018
* **Usuario de Slack**: sergiodxa
* **Usuario de Twitter**: https://twitter.com/sergiodxa
 **Otros usuarios**: https://sergiodxa.com <- mi blog
* **Pronombre**: El

### Recursos

* **Slides de la presentación**: Todavía no.
* **Repositorio de la charla**: Todavía no.

### Extra

* **¿Tenés la charla preparada?**: No todavía
* **¿A partir de qué mes la podrías dar?:** Voy a estar todo Septiembre.

> Avisanos si necesitás algo especial para poder dar la charla así lo podemos planificar con tiempo.

Adaptador USB-C a HDMI/VGA (lo que usen para proyectar)

**Comment by mateosilguero** [comment]
Gracias Sergio !
