### ISSUE TITLE
Life cycle de ensayo y error (react & Ab-testing)

### ISSUE THREAD

**Issue by mikerueda** [meetupjs-ar/charlas#88]
### Título
Life cycle de ensayo y error (React & Ab-testing)

### Descripción
¿Cómo enfrentar el desarrollo de un producto aún no definido? ¿y si la tecnología dada es desconocida también? Esta charla se trata sobre un viaje personal lleno de errores y buscando maximizar lo que puede aprender de ellos, a través de lo que hicimos en iúnigo al experimentar con una herramienta para... experimentos en un producto lleno de incertidumbres, de la mano de react.

### Tus datos

* **Bio**: Trabajo hace 14 años en productos digitales y desde 2012 estoy dedicado de enteramente a front-end. Precursor del Hate Driven Development. Dungeon master, serial drinker y docente.
* **Foto**: https://drive.google.com/file/d/15eRwqqXb7Lrukn2fnqwhtkRswd7P9OEb/view?usp=sharing
* **Usuario de Slack**: @mike (miguel rueda)
* **Usuario de Twitter**: @mikeledicen
* **Pronombre**: él / éste / ellos

### Recursos
Estas slides las usé en un draft de la charla hace varios meses y actualmente estoy trabajando en la versión 2 que es la que me gustaría exponer, pero sirven como referencia.
https://docs.google.com/presentation/d/12tYbHJflHmcFr7OsoejIfK4JsD0Msbqm6_QBzscfrj0/edit?usp=sharing

### Extra

* **¿Tenés la charla preparada?**: Si, aunque actualmente la estoy modificando un poco
* **¿A partir de qué mes la podrías dar?:** A partir de noviembre

> Avisanos si necesitás algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by mateosilguero** [comment]
Gracias Mike !
