### ISSUE TITLE
Hagamos del navegador, nuestro navegador

### ISSUE THREAD

**Issue by mblayer** [meetupjs-ar/charlas#89]
# ⚠️ IMPORTANTE

> Por favor, te pedimos que completes este issue con toda la información requerida y lo más detallado posible para evitar pedirte datos faltantes, de esta forma hacemos más eficiente el proceso de selección de charlas.

### Título
Hagamos del navegador, nuestro navegador.

### Descripción
Cuántas veces hemos bajado una extensión del navegador para cumplir una tarea o facilitar nuestro día a día? 
Nosotros podemos crear nuestras propias extensiones y poner a trabajar el navegador para nosotros. 
Conozcamos los primeros pasos  y acompáñenme a charlar sobre la experiencia de armarlas.

### Tus datos

* **Bio**: Matías es un desarrollador con muchos años de experiencia en javascript. Hoy en dia trabaja como frontend developer y Community Advocate en stensul generando espacios para la difusión de nuevas tecnologías, promoviendo y guiando a los desarrolladores para dar charlas sobre las tecnologías utilizadas en la empresa. También se desempeña como co-organizador de @vuenos_aires y Google Developer Expert en tecnologías web. Un apasionado por la fotografía y la robótica. Durante estos últimos años se dedicó a organizar eventos y espacios para la comunidad de desarrolladores brindando la posibilidad de acceso a las nuevas tecnologías de punta.
* **Foto**: Una URL (o subila acá) con una foto de perfil tuya para usar en el cover de youtube cuando subamos la charla.
* **Usuario de Slack**: @pelufito
* **Usuario de Twitter**: @m_blayer
* **Otros usuarios**: Si no tenés Twitter dejanos acá otros links donde te gustaría que te mencionemos en los tweets y otras publicaciones.
* **Pronombre**:

### Recursos

* **Slides de la presentación**: URL de la presentación (Si tenés).
* **Repositorio de la charla**: URL del repositorio con el código de la charla (Si tenés).

### Extra

* **¿Tenés la charla preparada?**: Si
* **¿A partir de qué mes la podrías dar?:** Diciembre

> Avisanos si necesitás algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by mateosilguero** [comment]
Gracias Mati !
