### ISSUE TITLE
Tu código puede ser mejor y puedo demostrarlo matemáticamente

### ISSUE THREAD

**Issue by mvaldesdeleon** [meetupjs-ar/charlas#9]
### Título

Tu código puede ser mejor y puedo demostrarlo matemáticamente
### Descripción

Programación funcional. El último grito de la moda, pero solo para aquellos dispuestos a sumergirse en la terminología. No más. Sin matemática ni formulas, la programación funcional ya esta entre nosotros, y ha llegado para quedarse. Con esta charla espero sacar a la luz distintos conceptos que ya manejamos en nuestro día a día, y demostrar que detrás de las palabras raras y los diagramas se esconde una herramienta más para hacer nuestro código más simple.
### Sobre el orador

**Sitio:** https://github.com/mvaldesdeleon
### Recursos

**Slides de la presentación:** http://fun.ction.al/es

**Repositorio de la charla:** https://github.com/mvaldesdeleon/functional-programming-es
### Extra

Tenes la charla preparada? Si

En qué mes la podrías dar? Octubre/Noviembre

**Comment by Villanuevand** [comment]
¡Que buen título! 
Ya quiero ir a verla...

**Comment by nicolasdanelon** [comment]
:+1: hay fecha?

**Comment by mvaldesdeleon** [comment]
Buenas.

Aviso que la charla ya esta lista, hoy hice un test run en el laburo. Por ahora anda por los 45'. Si es problema puedo ajustar los contenidos.

**Comment by nisnardi** [comment]
Por lo general tratamos que este dentro de los 30 minutos pero si consideras que son necesarios los 45, con gusto nos extendemos! Abrazo y gracias!

**Comment by gabmontes** [comment]
Muy buena la charla! Habría que cerrar el issue.
