### ISSUE TITLE
Docker desde las trincheras

### ISSUE THREAD

**Issue by gonrial** [meetupjs-ar/charlas#90]
### Título
Docker desde las trincheras

### Descripción
Salir a producción con una imagen de Docker con Nodejs implica tener en cuenta múltiples factores: testing, seguridad, healthchecks, dependencias con otros servicios.
La idea de la charla es mostrar detalles técnicos de Docker que permitan mejorar la experiencia de desarrollo y hacerlo compatible con las necesidades del equipo de operaciones.
Mostrar un par de buenas prácticas para Docker, Swarm y Kubernetes.

### Tus datos

* **Bio**: Ezequiel, AKA Peter, es un desarrollador experimentado que hace dos años pasó a hacer operaciones. Esto le trajo muchos dolores de cabeza y le permitió aprender mucho sobre las malas prácticas y cómo superarlas.
* **Foto**: https://avatars2.githubusercontent.com/u/475469
* **Usuario de Slack**: @peter
* **Usuario de Twitter**: @gonrial
* **Pronombre**: Peter

### Recursos

* **Slides de la presentación**: 
* **Repositorio de la charla**: 

### Extra

* **¿Tenés la charla preparada?**: En proceso.
* **¿A partir de qué mes la podrías dar?:** Febrero.

> Avisanos si necesitás algo especial para poder dar la charla así lo podemos planificar con tiempo.

**Comment by mateosilguero** [comment]
Gracias Peter !
