### ISSUE TITLE
Por qué no los dos?

### ISSUE THREAD

**Issue by mvaldesdeleon** [meetupjs-ar/charlas#92]
### Título
Por qué no los dos?, o "Sobre arquitectura, la grieta, y puertas giratorias"

### Descripción
-Monolito! -Microservicios! -Monolito! -Microservicios!
Con buenos argumentos de cada lado la discusión se repite a lo largo y a lo ancho, de equipo en equipo y de empresa en empresa.
Personalmente, creo que es momento de ponerle fin al debate de una vez por todas.
Que cómo? Con JavaScript, por supuesto!

### Tus datos

* **Bio**: Químico de formación, desarrollador de profesión. Me interesan demasiadas cosas como para hacer una lista. Vivo en Alemania desde hace 3 años y actualmente trabajo para AWS ayudando a distintas empresas en su viaje hacia la nube.
* **Foto**: https://i.imgur.com/nXRxVh1.jpg
* **Usuario de Slack**: @mvaldesdeleon
* **Usuario de Twitter**: @mvaldesdeleon
* **Pronombre**: El

### Recursos

* **Slides de la presentación**: TBD
* **Repositorio de la charla**: TBD

### Extra

* **¿Tenés la charla preparada?**: Si
* **¿A partir de qué mes la podrías dar?:** Mayo

**Comment by mateosilguero** [comment]
Gracias Martin !
