### ISSUE TITLE
Design systems - Un puente entre diseño y desarrollo

### ISSUE THREAD

**Issue by sebazelonka** [meetupjs-ar/charlas#93]
### Título
Design systems - Un puente entre diseño y desarrollo

### Descripción
Con la llegada de librerías como React.js, hoy más que nunca los componentes estan en su esplendor. 
La idea de ésta charla es entender por qué es una gran herramienta para acercar a los equipos de diseño y frontend, haciendo que el desarrollo sea mucho más agil, mejorando la experiencia de los desarrolladores y de los usuarios de nuestras apps.

### Tus datos

* **Bio**: Soy Sebastian Zelonka, trabajo en ank como Diseñador y colaboro con el equipo de Front End en el armado y mantenimiento de componentes (continuará...)
* **Foto**: https://ca.slack-edge.com/T0434657X-USL81AGLA-750fa19e2acb-512
* **Usuario de Slack**: Seba Zelonka
* **Usuario de Twitter**: sebazelonka
* **Otros usuarios**: Si no tenés Twitter dejanos acá otros links donde te gustaría que te mencionemos en los tweets y otras publicaciones.
* **Pronombre**: el 

### Recursos

* **Slides de la presentación**: URL de la presentación (Si tenés).
* **Repositorio de la charla**: URL del repositorio con el código de la charla (Si tenés).

### Extra

**¿Tenés la charla preparada?**: 
No todavía, necesito ayuda para prepararla porque solo es una idea. 
Tengo una base de los temas que podría tratar como disparador:
```
Temario
- Qué es un Design System
- Para qué sirve
- Quién está a cargo
- Flujo de trabajo "ideal"
    - Primero el componente o el diseño?
- Tools
    - Sketch/Figma/XD
    - React
    - Storybook
    - React Styleguidist
    - Zeplin
```

**¿A partir de qué mes la podrías dar?:** 
Fines de Julio creo que llego bien.

**Comment by mateosilguero** [comment]
Gracias seba !
