### ISSUE TITLE
W(hy)ASM 

### ISSUE THREAD

**Issue by lucas-aragno** [meetupjs-ar/charlas#96]
### Título
W(hy)ASM

### Descripción
Como, por que y por que no usar WASM en la web.

### Tus datos

* **Bio**:  Me pagan por estar en la computadora desde 2010. 
* **Foto**: 
![image](https://user-images.githubusercontent.com/5210254/86075604-c7ccc780-ba5e-11ea-896c-43f9f664c643.png)

* **Usuario de Slack**: laragno
* **Usuario de Twitter**: aragno157.
* **Pronombre**: he/him/his

### Recursos

* **Slides de la presentación**: TBD.
* **Repositorio de la charla**: TBD.

### Extra

* **¿Tenés la charla preparada?**: Si
* **¿A partir de qué mes la podrías dar?:** 2 dias despues de que me avisen asi subo todo

**Comment by durancristhian** [comment]
Gracias Lucas!
